# Generated by Django 4.2.4 on 2023-11-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GC', '0002_remove_usuario_password_usuario_apellidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(default='valor_predeterminado', max_length=128),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rut',
            field=models.CharField(default='N/A', max_length=12, unique=True),
        ),
    ]
