# Generated by Django 4.2.4 on 2023-11-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GC', '0004_curriculum'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudDeReemplazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('requisitos', models.TextField()),
                ('ubicacion', models.CharField(max_length=50)),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_de_trabajo', models.CharField(choices=[('Tiempo completo', 'Tiempo completo'), ('Medio tiempo', 'Medio tiempo'), ('Por horas', 'Por horas')], max_length=20)),
                ('tipo_de_contrato', models.CharField(choices=[('Indefinido', 'Indefinido'), ('Temporal', 'Temporal'), ('Freelance', 'Freelance'), ('Reemplazo', 'Reemplazo')], max_length=20)),
                ('area_de_trabajo', models.CharField(max_length=50)),
                ('fecha_de_publicacion', models.DateField(auto_now_add=True)),
                ('trabajo_remoto', models.BooleanField()),
                ('fecha_limite', models.DateField()),
            ],
        ),
    ]
