# Generated by Django 4.2.4 on 2023-11-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GC', '0005_solicituddereemplazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='correo_electronico',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
