# Generated by Django 4.2.4 on 2023-11-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GC', '0007_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='educacion',
            field=models.CharField(choices=[('basica', 'basica'), ('Media', 'Media'), ('Superior', 'Superior')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cv',
            name='experiencia_laboral',
            field=models.CharField(choices=[('Banco de chile', 'Banco de chile'), ('Falabella', 'Falabella'), ('Sodimac', 'Sodimac'), ('Entel', 'Entel'), ('Jumbo', 'Jumbo')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cv',
            name='habilidades',
            field=models.CharField(choices=[('Programacion', 'Programacion'), ('Primeros auxilios', 'Primeros auxilios'), ('Liderazgo', 'Liderazgo')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cv',
            name='idiomas',
            field=models.CharField(choices=[('Español', 'Español'), ('Ingles', 'Ingles'), ('Español e ingles', 'Español e ingles'), ('Español, ingles y frances', 'Español, ingles y frances'), ('Español, ingles y portugues', 'Español, ingles y portugues')], max_length=30),
        ),
    ]
