# Generated by Django 4.2.4 on 2023-11-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GC', '0008_alter_cv_educacion_alter_cv_experiencia_laboral_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='experiencia_laboral',
            field=models.CharField(choices=[('Asistente ejecutivo', 'Asistente ejecutivo'), ('Coordinador de proyecto', 'Coordinador de proyecto'), ('Gerente seguridad', 'Gerente seguridad'), ('Desarrollador backend', 'Desarrollador backend'), ('Desarrollador frontend', 'Desarrollador frontend'), ('Desarrollador full stack', 'Desarrollador full stack')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cv',
            name='habilidades',
            field=models.CharField(choices=[('Programacion', 'Programacion'), ('Primeros auxilios', 'Primeros auxilios'), ('Liderazgo', 'Liderazgo'), ('Creatividad e innovación', 'Creatividad e innovación'), ('Trabajo en equipo', 'Trabajo en equipo')], max_length=30),
        ),
    ]
