# Generated by Django 4.2.4 on 2023-11-10 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GC', '0009_alter_cv_experiencia_laboral_alter_cv_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicituddereemplazo',
            name='abierto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='solicituddereemplazo',
            name='cve',
            field=models.ManyToManyField(related_name='solicitudes', to='GC.cv'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cve',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GC.cv'),
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud_reemplazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GC.solicituddereemplazo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GC.usuario')),
            ],
        ),
    ]
