# Generated by Django 4.2.4 on 2023-11-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GC', '0010_solicituddereemplazo_abierto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='postulacion',
            name='puntaje',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solicituddereemplazo',
            name='educacion_requerida',
            field=models.CharField(choices=[('basica', 'basica'), ('Media', 'Media'), ('Superior', 'Superior')], default='basica', max_length=30),
        ),
        migrations.AddField(
            model_name='solicituddereemplazo',
            name='experiencia_requerida',
            field=models.CharField(choices=[('Asistente ejecutivo', 'Asistente ejecutivo'), ('Coordinador de proyecto', 'Coordinador de proyecto'), ('Gerente seguridad', 'Gerente seguridad'), ('Desarrollador backend', 'Desarrollador backend'), ('Desarrollador frontend', 'Desarrollador frontend'), ('Desarrollador full stack', 'Desarrollador full stack')], default='Asistente ejecutivo', max_length=30),
        ),
        migrations.AddField(
            model_name='solicituddereemplazo',
            name='habilidades_requeridas',
            field=models.ManyToManyField(to='GC.habilidad'),
        ),
    ]
