# Generated by Django 4.2.4 on 2023-11-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GC', '0011_habilidad_postulacion_puntaje_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='solicituddereemplazo',
            name='area_de_trabajo',
            field=models.CharField(choices=[('Tecnología', 'Tecnología'), ('Salud', 'Salud'), ('Finanzas', 'Finanzas'), ('Educación', 'Educación'), ('Marketing', 'Marketing'), ('Ventas', 'Ventas'), ('Recursos Humanos', 'Recursos Humanos'), ('Ingeniería', 'Ingeniería'), ('Arte y Diseño', 'Arte y Diseño'), ('Legal', 'Legal'), ('Medio Ambiente', 'Medio Ambiente'), ('Investigación', 'Investigación'), ('Servicios Sociales', 'Servicios Sociales'), ('Otros', 'Otros')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='solicituddereemplazo',
            name='experiencia_requerida',
        ),
        migrations.AlterField(
            model_name='solicituddereemplazo',
            name='ubicacion',
            field=models.CharField(choices=[('iquique', 'iquique'), ('alto_hospicio', 'alto_hospicio')], max_length=50),
        ),
        migrations.AddField(
            model_name='solicituddereemplazo',
            name='experiencia_requerida',
            field=models.ManyToManyField(to='GC.experiencia'),
        ),
    ]
