# Generated by Django 4.2.4 on 2023-11-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GC', '0014_usuario_habilidades_pos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='habilidades_pos',
            new_name='habilidades_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='experiencia_usuario',
            field=models.CharField(choices=[('asistente_ejecutivo', 'asistente_ejecutivo'), ('coordinador_proyecto', 'coordinador_proyecto'), ('gerente_de_seguridad', 'gerente_de_seguridad'), ('desarrollador_backend', 'desarrollador_backend'), ('desarrollador_frontend', 'desarrollador_frontend'), ('desarrollador_full_stack', 'desarrollador_full_stack'), ('especialista_en_recursos_humanos', 'especialista_en_recursos_humanos'), ('especialista_en_ventas', 'especialista_en_ventas'), ('especialista_en_soporte Técnico', 'especialista_en_soporte Técnico'), ('especialista_en_logística', 'especialista_en_logística'), ('analista_financiero', 'analista_financiero')], default='asistente_ejecutivo', max_length=50),
        ),
    ]
