# Generated by Django 4.2.4 on 2023-11-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trabajos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicituddetrabajo',
            name='especialidades_buscadas',
        ),
        migrations.RemoveField(
            model_name='solicituddetrabajo',
            name='id',
        ),
        migrations.AddField(
            model_name='solicituddetrabajo',
            name='codigo',
            field=models.CharField(default=None, max_length=6, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Especialidad',
        ),
    ]
