# Generated by Django 4.2.4 on 2023-11-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trabajos', '0002_remove_solicituddetrabajo_especialidades_buscadas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicituddetrabajo',
            name='codigo',
        ),
        migrations.AddField(
            model_name='solicituddetrabajo',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
