# Generated by Django 4.2.4 on 2023-11-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trabajos', '0004_solicituddetrabajo_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicituddetrabajo',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='solicituddetrabajo',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
